Unindo os Dataframes

In [24]:
import pandas as pd

#importando os dados formatados de cada dataframe
df_Inmet = "dados_formatados/FORTALEZA_DADOS_CLIMATICOS.csv"
df_Infodengue = "dados_formatados/INFODENGUE_DADOS_FORTALEZA.CSV"
df_saneamento = "dados_formatados/SANEAMENTO_DADOS_FORTALEZA.csv"

df_Inmet = pd.read_csv(df_Inmet, sep=';', decimal=',', encoding='utf-8-sig')
df_Infodengue = pd.read_csv(df_Infodengue)
df_saneamento = pd.read_csv(df_saneamento)

# 1. Unindo Clima com Dengue
df_final = pd.merge(df_Inmet, df_Infodengue, on='MES_REFERENCIA', how='left')

# 2. Unindo o resultado com Saneamento
df_final = pd.merge(df_final, df_saneamento, on='MES_REFERENCIA', how='left')

# 3. Preenchendo buracos (se houver meses sem registro de dengue)
df_final = df_final.fillna(0)

df_final

,MES_REFERENCIA,Chuva_Acumulada,Temp_Media_Mensal,Umid_Media,Pres_Media,casos_mensais,nivel_alerta,Ano,Pop_sem_coleta_esgoto,Perc_sem_coleta_esgoto
0,2017-01-01,105.2,27.65,72.81,1008.44,3328.0,2,2017.0,1294695.0,0.493
1,2017-02-01,209.6,27.30,75.68,1008.18,5050.0,3,2017.0,1294695.0,0.493
2,2017-03-01,475.0,26.46,82.21,1008.32,8238.0,4,2017.0,1294695.0,0.493
3,2017-04-01,334.2,27.07,79.31,1008.42,14309.0,4,2017.0,1294695.0,0.493
4,2017-05-01,129.8,27.29,76.54,1009.36,3780.0,2,2017.0,1294695.0,0.493
...,...,...,...,...,...,...,...,...,...,...
92,2024-09-01,0.0,30.65,50.30,1010.44,444.0,1,2024.0,920871.0,0.358
93,2024-10-01,0.0,30.94,50.61,1009.69,317.0,1,2024.0,920871.0,0.358
94,2024-11-01,0.0,31.24,50.91,1008.93,421.0,1,2024.0,920871.0,0.358
95,2024-12-01,0.0,30.91,56.85,1008.67,346.0,1,2024.0,920871.0,0.358
96,2025-01-01,0.0,30.26,62.79,1008.64,455.0,1,0.0,0.0,0.000

Padronização de nomes das colunas

In [25]:
print(df_final.columns)

Index(['MES_REFERENCIA', 'Chuva_Acumulada', 'Temp_Media_Mensal', 'Umid_Media',
       'Pres_Media', 'casos_mensais', 'nivel_alerta', 'Ano',
       'Pop_sem_coleta_esgoto', 'Perc_sem_coleta_esgoto'],
      dtype='str')

In [26]:
#fazendo alteração dos nome de cada coluna
df_final = df_final.rename(columns={
    'MES_REFERENCIA': 'MESES DE REFERÊNCIA',
    'Temp_Media_Mensal' : 'TEMPERATURA MÉDIA MENSAL (°C)',
    'Umid_Media' : 'UMIDADE MÉDIA (%)',
    'Pres_Media' : 'PRESSÃO MÉDIA (hPa)',
    'casos_mensais' : 'CASOS DE DENGUE (NÚMERO DE CASOS)',
    'nivel_alerta' : 'NÍVEL DE ALERTA - DENGUE (0-3)',
    'Pop_sem_coleta_esgoto' : 'POPULAÇÃO SEM COLETA DE ESGOTO (NÚMERO DE PESSOAS)',
    'Perc_sem_coleta_esgoto' : 'PERCENTUAL SEM COLETA DE ESGOTO (%)'
})

df_final

,MESES DE REFERÊNCIA,Chuva_Acumulada,TEMPERATURA MÉDIA MENSAL (°C),UMIDADE MÉDIA (%),PRESSÃO MÉDIA (hPa),CASOS DE DENGUE (NÚMERO DE CASOS),NÍVEL DE ALERTA - DENGUE (0-3),Ano,POPULAÇÃO SEM COLETA DE ESGOTO (NÚMERO DE PESSOAS),PERCENTUAL SEM COLETA DE ESGOTO (%)
0,2017-01-01,105.2,27.65,72.81,1008.44,3328.0,2,2017.0,1294695.0,0.493
1,2017-02-01,209.6,27.30,75.68,1008.18,5050.0,3,2017.0,1294695.0,0.493
2,2017-03-01,475.0,26.46,82.21,1008.32,8238.0,4,2017.0,1294695.0,0.493
3,2017-04-01,334.2,27.07,79.31,1008.42,14309.0,4,2017.0,1294695.0,0.493
4,2017-05-01,129.8,27.29,76.54,1009.36,3780.0,2,2017.0,1294695.0,0.493
...,...,...,...,...,...,...,...,...,...,...
92,2024-09-01,0.0,30.65,50.30,1010.44,444.0,1,2024.0,920871.0,0.358
93,2024-10-01,0.0,30.94,50.61,1009.69,317.0,1,2024.0,920871.0,0.358
94,2024-11-01,0.0,31.24,50.91,1008.93,421.0,1,2024.0,920871.0,0.358
95,2024-12-01,0.0,30.91,56.85,1008.67,346.0,1,2024.0,920871.0,0.358
96,2025-01-01,0.0,30.26,62.79,1008.64,455.0,1,0.0,0.0,0.000

Verificação de periodo

In [ ]:
# Verificando o intervalo de datas
print(df_final['MESES DE REFERÊNCIA'].min())
print(df_final['MESES DE REFERÊNCIA'].max())

print("-" * 50)

# Verificando se há valores nulos
print(df_final.isnull().sum())

2017-01-01
2025-01-01
MESES DE REFERÊNCIA                                   0
Chuva_Acumulada                                       0
TEMPERATURA MÉDIA MENSAL (°C)                         0
UMIDADE MÉDIA (%)                                     0
PRESSÃO MÉDIA (hPa)                                   0
CASOS DE DENGUE (NÚMERO DE CASOS)                     0
NÍVEL DE ALERTA - DENGUE (0-3)                        0
Ano                                                   0
POPULAÇÃO SEM COLETA DE ESGOTO (NÚMERO DE PESSOAS)    0
PERCENTUAL SEM COLETA DE ESGOTO (%)                   0
dtype: int64

Exportando o dataframe

In [27]:
#Exportando o dataset final para csv
df_final.to_csv('dados_formatados/FORTALEZA_OBS_COMPLETO.csv', sep=';', decimal=',', index=False, encoding='utf-8-sig')
print(f"\nSUCESSO! Total de {len(df_final)} linhas consolidadas em 'FORTALEZA_DADOS_CLIMATICOS_DENGUE_SANEAMENTO.csv'")

SUCESSO! Total de 97 linhas consolidadas em 'FORTALEZA_DADOS_CLIMATICOS_DENGUE_SANEAMENTO.csv'