Unindo os Dataframes

In [1]:
import pandas as pd

#importando os dados formatados de cada dataframe
df_Inmet = "dados_formatados/FORTALEZA_DADOS_CLIMATICOS.csv"
df_Infodengue = "dados_formatados/INFODENGUE_DADOS_FORTALEZA.CSV"
df_saneamento = "dados_formatados/SANEAMENTO_DADOS_FORTALEZA.csv"

df_Inmet = pd.read_csv(df_Inmet, sep=';', decimal=',', encoding='utf-8-sig')
df_Infodengue = pd.read_csv(df_Infodengue)
df_saneamento = pd.read_csv(df_saneamento)

# 1. Unindo Clima com Dengue
df_final = pd.merge(df_Inmet, df_Infodengue, on='MES_REFERENCIA', how='left')

# 2. Unindo o resultado com Saneamento
df_final = pd.merge(df_final, df_saneamento, on='MES_REFERENCIA', how='left')

# 3. Preenchendo buracos (se houver meses sem registro de dengue)
df_final = df_final.fillna(0)

df_final

,MES_REFERENCIA,Chuva_Acumulada,Temp_Media_Mensal,Umid_Media,Pres_Media,chikungunya,dengue,zika,total_arboviroses,nivel_alerta,Pop_sem_coleta_esgoto,Perc_sem_coleta_esgoto
0,2010-01-01,53.4,28.30,70.43,1008.16,0.0,388.0,0.0,388.0,1.0,1267675.0,0.517
1,2010-02-01,73.4,28.55,72.44,1007.43,0.0,301.0,0.0,301.0,1.0,1267675.0,0.517
2,2010-03-01,39.2,28.86,70.78,1007.99,0.0,337.0,0.0,337.0,1.0,1267675.0,0.517
3,2010-04-01,0.0,28.66,69.44,1008.21,0.0,388.0,0.0,388.0,1.0,1267675.0,0.517
4,2010-05-01,0.0,28.47,68.10,1008.43,0.0,514.0,0.0,514.0,1.0,1267675.0,0.517
...,...,...,...,...,...,...,...,...,...,...,...,...
176,2024-09-01,0.0,30.65,50.30,1010.44,57.0,444.0,0.0,501.0,1.0,920871.0,0.358
177,2024-10-01,0.0,30.94,50.61,1009.69,30.0,317.0,0.0,347.0,1.0,920871.0,0.358
178,2024-11-01,0.0,31.24,50.91,1008.93,30.0,421.0,0.0,451.0,1.0,920871.0,0.358
179,2024-12-01,0.0,30.91,56.85,1008.67,27.0,274.0,0.0,301.0,1.0,920871.0,0.358
180,2025-01-01,0.0,30.26,62.79,1008.64,0.0,0.0,0.0,0.0,0.0,0.0,0.000

Padronização de nomes das colunas

In [2]:
print(df_final.columns)

Index(['MES_REFERENCIA', 'Chuva_Acumulada', 'Temp_Media_Mensal', 'Umid_Media',
       'Pres_Media', 'chikungunya', 'dengue', 'zika', 'total_arboviroses',
       'nivel_alerta', 'Pop_sem_coleta_esgoto', 'Perc_sem_coleta_esgoto'],
      dtype='str')

In [ ]:
#fazendo alteração dos nome de cada coluna
df_final = df_final.rename(columns={
    'MES_REFERENCIA': 'MESES DE REFERÊNCIA',
    'Temp_Media_Mensal' : 'TEMPERATURA MÉDIA MENSAL (°C)',
    'Umid_Media' : 'UMIDADE MÉDIA (%)',
    'Pres_Media' : 'PRESSÃO MÉDIA (hPa)',
    'casos_mensais' : 'CASOS DE DENGUE (NÚMERO DE CASOS)',
    'nivel_alerta' : 'NÍVEL DE ALERTA - DENGUE (0-3)',
    'Pop_sem_coleta_esgoto' : 'POPULAÇÃO SEM COLETA DE ESGOTO (NÚMERO DE PESSOAS)',
    'Perc_sem_coleta_esgoto' : 'PERCENTUAL SEM COLETA DE ESGOTO (%)',
    'total_arboviroses' : 'Total Arboviroses'
})

df_final

,MESES DE REFERÊNCIA,Chuva_Acumulada,TEMPERATURA MÉDIA MENSAL (°C),UMIDADE MÉDIA (%),PRESSÃO MÉDIA (hPa),chikungunya,dengue,zika,Total Arboviroses,NÍVEL DE ALERTA - DENGUE (0-3),POPULAÇÃO SEM COLETA DE ESGOTO (NÚMERO DE PESSOAS),PERCENTUAL SEM COLETA DE ESGOTO (%)
0,2010-01-01,53.4,28.30,70.43,1008.16,0.0,388.0,0.0,388.0,1.0,1267675.0,0.517
1,2010-02-01,73.4,28.55,72.44,1007.43,0.0,301.0,0.0,301.0,1.0,1267675.0,0.517
2,2010-03-01,39.2,28.86,70.78,1007.99,0.0,337.0,0.0,337.0,1.0,1267675.0,0.517
3,2010-04-01,0.0,28.66,69.44,1008.21,0.0,388.0,0.0,388.0,1.0,1267675.0,0.517
4,2010-05-01,0.0,28.47,68.10,1008.43,0.0,514.0,0.0,514.0,1.0,1267675.0,0.517
...,...,...,...,...,...,...,...,...,...,...,...,...
176,2024-09-01,0.0,30.65,50.30,1010.44,57.0,444.0,0.0,501.0,1.0,920871.0,0.358
177,2024-10-01,0.0,30.94,50.61,1009.69,30.0,317.0,0.0,347.0,1.0,920871.0,0.358
178,2024-11-01,0.0,31.24,50.91,1008.93,30.0,421.0,0.0,451.0,1.0,920871.0,0.358
179,2024-12-01,0.0,30.91,56.85,1008.67,27.0,274.0,0.0,301.0,1.0,920871.0,0.358
180,2025-01-01,0.0,30.26,62.79,1008.64,0.0,0.0,0.0,0.0,0.0,0.0,0.000

Verificação de periodo

In [5]:
# Verificando o intervalo de datas
print(df_final['MESES DE REFERÊNCIA'].min())
print(df_final['MESES DE REFERÊNCIA'].max())

print("-" * 50)

# Verificando se há valores nulos
print(df_final.isnull().sum())

2010-01-01
2025-01-01
--------------------------------------------------
MESES DE REFERÊNCIA                                   0
Chuva_Acumulada                                       0
TEMPERATURA MÉDIA MENSAL (°C)                         0
UMIDADE MÉDIA (%)                                     0
PRESSÃO MÉDIA (hPa)                                   0
chikungunya                                           0
dengue                                                0
zika                                                  0
Total Arboviroses                                     0
NÍVEL DE ALERTA - DENGUE (0-3)                        0
POPULAÇÃO SEM COLETA DE ESGOTO (NÚMERO DE PESSOAS)    0
PERCENTUAL SEM COLETA DE ESGOTO (%)                   0
dtype: int64

Exportando o dataframe

In [6]:
#Exportando o dataset final para csv
df_final.to_csv('dados_formatados/FORTALEZA_OBS_COMPLETO.csv', sep=';', decimal=',', index=False, encoding='utf-8-sig')
print(f"\nSUCESSO! Total de {len(df_final)} linhas consolidadas em 'FORTALEZA_DADOS_CLIMATICOS_DENGUE_SANEAMENTO.csv'")

SUCESSO! Total de 181 linhas consolidadas em 'FORTALEZA_DADOS_CLIMATICOS_DENGUE_SANEAMENTO.csv'

Novo bloco: usar pipeline compartilhado e gerar os graficos da analise

In [7]:
from src.data.consolidation_pipeline import build_consolidated_dataframe
from src.analysis.climate_health_analysis import main as run_climate_analysis

# Mesmo pipeline compartilhado entre notebook e script
df_pipeline = build_consolidated_dataframe()
print(f"Pipeline compartilhado carregado com {len(df_pipeline)} linhas.")

# Gera todos os graficos e artefatos em data/processed/analise_climatica
run_climate_analysis()

Pipeline compartilhado carregado com 181 linhas.

ValueError: Colunas obrigatórias ausentes: ['casos_dengue']